name: Run Tests and Validate Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build project
        run: cargo build

      - name: Run tests
        run: cargo test -- --nocapture

  deploy:
    needs: test
    if: ${
    runs-on: ubuntu-latest

    steps:
      - name: All tests passed
        run: echo "All tests passed."
